# Generated by Django 4.0.3 on 2022-03-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(default='https://github.com/lheredias/comics-site/blob/main/screenshots/00.png?raw=true'),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='short summary'),
        ),
    ]
