# Generated by Django 4.0.3 on 2022-03-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='labels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
