# Generated by Django 4.0.3 on 2022-04-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_github_post_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_set', models.JSONField()),
                ('skill_category', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
